server:
  port: 80

spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://114.115.246.166:9411
  sleuth:
    sampler:
      # 采样率值介于0到1之间，1则表示全部采集
      probability: 1
#  main:
#    allow-circular-references: true

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true.
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息,默认为true
    fetch-registry: true
    #从注册中心获取访问地址
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
