server:
  port: 9004

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 114.115.246.166:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'