server:
  port: 80

#服务别名
spring:
  application:
    name: consul-consumer-payment
    #consul
  cloud:
    consul:
      host: 114.115.246.166
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
