server:
  port: 8803
spring:
  application:
    name: cloud-stream-consumer
  rabbitmq:
    host: 114.115.246.166
    port: 5672
    username: admin
    password: 847144514
  cloud:
    stream:
      bindings: # 服务的整合处理
        myChannel-in-0: # 这个名字是一个通道的名称
          destination: staudyExchange # 表示要使用的Exchange名称定义
          content-type: application/json  #设置消息类型，本次为json， 文本则设置"text/plain”
          group: groupA #设置相同分组，不重复消费

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    instance:
      lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔(默认是30秒)
      lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒的间隔(默认是90秒)
      instance-id: send-8803.com #在信息列表时显示主机名称
      prefer-ip-address: true #访问的路径变为IP地址
