server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://114.115.246.166:9411
  sleuth:
    sampler:
      # 采样率值介于0到1之间，1则表示全部采集
      probability: 1
  datasource:
    username: root
    password: 847144514
    url: jdbc:mysql://114.115.246.166:3306/db2019?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true.
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息,默认为true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true #访问路径可以显示IP


mybatis:
  type-aliases-package: com.srz.springcloud.entities
  mapper-locations: classpath:mapper/*.xml